create table if not exists historical_prices (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date       date not null unique,   -- one row per day; required for upsert on "date"
  price      numeric not null
);

alter table historical_prices enable row level security;

drop policy if exists "Public read access" on historical_prices;
create policy "Public read access"
  on historical_prices for select
  using (true);
